[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
